CREATE TABLE IF NOT EXISTS auth.users (
id SERIAL PRIMARY KEY,
username varchar(50) UNIQUE,
email varchar(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(20) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);